CREATE TABLE PLAYER(
	ID					INTEGER NOT NULL AUTO_INCREMENT,
	FIRST_NAME			VARCHAR(25) NOT NULL,
	LAST_NAME			VARCHAR(25) NOT NULL,
	EMAIL				VARCHAR(50),
	DATE_OF_BIRTH		DATE NOT NULL,
	ADDRESS_STREET		VARCHAR(35),
	ADDRESS_CITY		VARCHAR(35),
	ADDRESS_STATE		VARCHAR(2),
	ADDRESS_ZIP_CODE 	VARCHAR(20),
	PHONE_NUMBER		VARCHAR(42),
	JERSEY_NUMBER		INTEGER NOT NULL,
	HOME_TOWN           VARCHAR(25),
	POSITION            VARCHAR(20),
	STATUS			    VARCHAR(8) NOT NULL
);

CREATE TABLE SCHEDULE(
	ID					INTEGER NOT NULL AUTO_INCREMENT,
	DESCRIPTION			VARCHAR(25) NOT NULL,
	LEAGUE			    VARCHAR(25) NOT NULL
);

CREATE TABLE GAME(
	ID						INTEGER NOT NULL AUTO_INCREMENT,
	SCHEDULE_ID				INTEGER NOT NULL,
	GAME_DATE		    	DATE NOT NULL,
	GAME_TIME				TIME NOT NULL,
	OPPONENT				VARCHAR(25) NOT NULL,
	HOME_OR_AWAY			VARCHAR(20),
	PLAYER_ON_BEVARAGE_DUTY INTEGER
);