CREATE TABLE PLAYER(
	ID					INTEGER NOT NULL AUTO_INCREMENT,
	FIRST_NAME			VARCHAR(25) NOT NULL,
	LAST_NAME			VARCHAR(25) NOT NULL,
	EMAIL				VARCHAR(50),
	DATE_OF_BIRTH		DATE NOT NULL,
	ADDRESS_STREET		VARCHAR(35),
	ADDRESS_CITY		VARCHAR(35),
	ADDRESS_STATE		VARCHAR(2),
	ADDRESS_ZIP_CODE 	VARCHAR(20),
	PHONE_NUMBER		VARCHAR(42),
	JERSEY_NUMBER		INTEGER NOT NULL,
	STATUS			    VARCHAR(4) NOT NULL
);
