CREATE TABLE PLAYER(
	ID					INTEGER NOT NULL AUTO_INCREMENT,
	FIRST_NAME			VARCHAR(25) NOT NULL,
	LAST_NAME			VARCHAR(25) NOT NULL,
	EMAIL				VARCHAR(50) NOT NULL,
	DATE_OF_BIRTH		DATE NOT NULL,
	ADDRESS_STREET		VARCHAR(35) NOT NULL,
	ADDRESS_CITY		VARCHAR(35) NOT NULL,
	ADDRESS_STATE		VARCHAR(2) NOT NULL,
	ADDRESS_ZIP_CODE 	VARCHAR(20) NOT NULL,
	PHONE_NUMBER		INTEGER,
	JERSEY_NUMBER		INTEGER NOT NULL,
	STATUS			    VARCHAR(4) NOT NULL
);
